// <auto-generated />
namespace EF_Test.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Inital : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201309050247210_Inital"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X3W7TShC+PxLvYO0VXJANRUJQOaCSNqg6pK1wD/cTe5Ku2B/jXVfJs3HBI/EKZ9b/sZM2AY4Od/Z45ptvZ+fbWf/49j18t1YyuMfMCqMn7MVozALUsUmEXk1Y7pbPX7N3b5/8FV4kah18rv1OvB9Fajthd86lp5zb+A4V2JEScWasWbpRbBSHxPCT8fg1fzHmSBCMsIIg/JRrJxQWL/Q6NTrG1OUg5yZBaSs7fYkK1OAKFNoUYpywi9ktWseCMymAskcol0dSGb/xVFiThNJcEB23ud2kWKSasBtaqdFdH/L6GzdbBjLdZCbFzG0+4bKKvExYwLfjeD+wCevE+OT0pN3LExZc5VLCQpJhCdIiC9JXp5EzGX5AjRk4TG7AOcy0j8WCfFWE0/TVYXV4w8cnvg4ctDYOHO3rgHiP5kxk1vnHmm3kMuoTFszEGpOPqFfurmE8h3VtoUcW/KMFtRUFuSzH7grL94czf4T/KfHFHIT8j7OGvG2/YVOSNhwI2vWaUdH/3opr12vQMiJC13SxSSVla/FLwYyq9t5Jo0nYqpCXMqzlyvfoNZxDmlKFOvqtLEFUinf6PDperKrE4LHdodmGbZOJZAIr7H2l1MS0aOBzcLAAv2fTRA3cDipvnWuryv2joS167e6fu5s42nXKdMs2o5UoknexKGzS7z6eqtAoBgnZjgNmamSu9L5D6qHoju67IB3z4VitkrtQrfVwpEqaXZjKNMQIea+i/c3ig93qHeH9vX9IOH2XJnsjoJ5QwqppH59+gy4uXVhAxbkXie/gaGMdqpF3GEVf5VQKWm/rMActltR8t+YL+klOIvv5YdoMEWsT+WdOVOEX/+jsHAzcIyehvocsvoPsqYL1s1+dbr8EtjWxjkA6bgoNT9PHJlE5cPZOorKPJyxZGCJfkqzH109OqaGoQt69eIbnaMWqhfDXUI2xvwm1oLXPpV6autK0rC6j2qW3EXN0kFB1zjInlhA7+hyjtcUN4jPI3O+VWmByqa9zl+buzFpUC7nprjfkD+cvRvE25/A69W/2dyyBaApaAl7r97mQScN7NtTIPgjfKJXwiBXdoAhutWmQrow+EKgq3zmmqL1sb1GlksDstY7gHvdze7yG2xULzwWsMlDdCpaWikkEaqstKUE3os3n/5u4/3F6+y9O/LPEag0AAA=="; }
        }
    }
}
