// <auto-generated />
namespace EF_Test.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class CarObject : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201309120209095_Car Object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1YS27bSBDdB5g7EFzNLKJWPECQGFQCj2wNjES2EToBsmyRRbkx/eGwm4Z0tixypFwh1fw2ScmS7NjJIjuy2PXqy6pHfvvyNXi7Ety7hUwzJSf+i9HY90BGKmZyOfFzkzx/5b9988ez4CwWK+9Tfe7InkNNqSf+jTHpMSE6ugFB9UiwKFNaJWYUKUForMjRePyKvBgTQAgfsTwv+JBLwwQUN3g7VTKC1OSUz1UMXFdyfBIWqN4FFaBTGsHEP5tdgza+d8IZResh8ORAV8avrSt+YwTNnKE7Zn29TqEwNfGvMFIl3TN46h2sOwIUXWUqhcysP0BSaZ7Hvke6eqSv2Kg5OtY4Xknz95HvXeSc0wVHQUK5Bt9LXx6HRmXwL0jIqIH4ihoDmbS6UDhfJeE4fblfHl6T8ZHNA6FSKkMN1nXgeM/NGcu0sZe1t6HJsE98b8ZWEL8HuTQ3jcdzuqoleOl7HyXDtkIlk+XgRlje3235Pf1Jhs/mlPFHthqQtv3ubMopzX53ZMfNebJ88pYoRtSTW/0MWPxtJTm0p3DeGsqwbnWXFzPVSmFlei1WaoRgmsmoUo7WWvxyCI+qkdmPo6+PTaw3aNve3hhB42u7FEi5FertQbasj2BO0xSr46yTSuKF5S6ZPg8P3x2ixCCR3rBCGm8bS/iO0CX0nqJp9LSYp6fU0AW1/TKNxeDYXpWpbXUK1J8Lbcbr4/barf9o09Jz0zbDSAS+20VQ0JjfvC0r1TCinGYbpstU8VzIbRPqLm1nDbkgjnh/rHaxuFCtdH+kalO4MJVoiBGQXkb7xSKDavXmd7/2e3VG8erdoy8Ge2evptio9TgdUawBV70QHKBfjvQOQinaH6Mc0C5EKXni6g/GZv9IY70Zn70xGVQjazcVH8yw8ojvYWpuWWznV7jWBsTIHhiF//MpZxhve2BOJUuwxa7Vf2A/K3DE3p/ZN/xB65j/mvSe2eB30qYB1zqQlstbmkU3NPtT0NVfD6XaDwLr0OcDkH5tSvwoVXSo7INS3qGnD0JyKWcR8o8jnEP2s4t0ltxyK+ksJ8/EjxcKXS6drJnqbkK6jY9uQi356z2Z6nC0BsT9FxKcgmbLFsL+GZEQ2U+hFrQ+cy4TVZcMw3E9qo/0ewMMjTHjJ5lhCY0MPo5A6+IL5hPluX1jxQLic3mZmzQ3J1qDWPC1G29A7rZf0PGuz8Flau/0jwgB3WQYAlzKf3LG48bv2fAd2wZhm696cdEr/IJDuOW6QbpQck+gKn2nkIK0r/01iJQjmL6UIb2F7b7tzmE3Y8Epo8uMCjeDpaTyJKSi0+powNVo7dlfecT+y3vzHZizEAr9EwAA"; }
        }
    }
}
